name: Unit Tests

on: [push]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Package install
        working-directory: ./mobile-app
        run: npm install --force

      - name: Tests
        working-directory: ./mobile-app
        run: npm test
